name: Build and push Docker image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: basit56700/mern_stack:social

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}
